[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "psutil>=7.0.0",
    "pywinauto>=0.6.9",
    "watchdog>=6.0.0",
]
